//! Clap CLI surface for the `air-drive` binary.
//!
//! Single source of truth for the user-visible commands documented in
//! `contracts/cli.md`. Each subcommand resolves to one of [`Command`]'s variants and
//! is dispatched via [`Cli::dispatch`] — the actual subcommand handlers live in
//! sibling modules (link.rs, map.rs, …) and are wired in Phase 3+.

use std::path::PathBuf;

use clap::{Parser, Subcommand};

/// Top-level CLI definition. Generated by clap from the struct.
#[derive(Debug, Parser)]
#[command(
    name = "air-drive",
    version,
    about = "Open source Google Drive sync daemon for Linux",
    long_about = None,
)]
pub struct Cli {
    /// Override the XDG config directory (default `$XDG_CONFIG_HOME/air-drive`).
    #[arg(long, global = true, value_name = "PATH")]
    pub config_dir: Option<PathBuf>,

    /// Duplicate logs to this file in addition to stderr.
    #[arg(long, global = true, value_name = "PATH")]
    pub log_file: Option<PathBuf>,

    /// Increase log verbosity. Repeatable: `-v` info, `-vv` debug, `-vvv` trace.
    #[arg(short = 'v', long, global = true, action = clap::ArgAction::Count)]
    pub verbose: u8,

    /// Disable the post-install rclone auto-download. The daemon will fail at startup
    /// if `rclone` is not found via config / `$PATH` / cache.
    #[arg(long, global = true)]
    pub no_download_rclone: bool,

    /// Subcommand to dispatch.
    #[command(subcommand)]
    pub command: Command,
}

/// Every subcommand of `air-drive`. See `contracts/cli.md`.
#[derive(Debug, Subcommand)]
pub enum Command {
    /// Link a Google Drive account via the desktop OAuth flow (FR-001).
    Link {
        /// Human-friendly label stored alongside the account. Defaults to the
        /// captured email.
        #[arg(long, value_name = "LABEL")]
        account_label: Option<String>,
    },
    /// Record the local↔remote folder mapping (FR-002).
    Map {
        /// Local folder path (created on the fly if missing — FR-002).
        local_path: PathBuf,
        /// Remote folder, one of: Drive file ID, Drive folder URL, or
        /// `path:My Drive/Sync` notation.
        remote_folder: String,
    },
    /// Run the daemon in the foreground (FR-014, FR-017).
    Start {
        /// Perform initial reconciliation if `drive_change_cursor` is empty.
        #[arg(long)]
        initial_sync: bool,
        /// Override `daemon.remote_poll_interval_seconds` (clamped to 10..=60).
        #[arg(long, value_name = "SECONDS")]
        remote_poll_interval: Option<u64>,
    },
    /// Signal a running daemon to pause sync (FR-015).
    Pause,
    /// Signal a paused daemon to resume sync (FR-015).
    Resume,
    /// Print the current daemon state (FR-008).
    Status {
        /// Emit JSON matching `contracts/status.schema.json` instead of the
        /// human-readable summary.
        #[arg(long)]
        json: bool,
    },
    /// Remove the linked account, tokens, and mapping (FR-018, FR-019).
    Unlink {
        /// Skip the interactive confirmation prompt.
        #[arg(short = 'y', long)]
        yes: bool,
    },
    /// Interactive first-time setup: link → map → start --initial-sync.
    Setup {
        /// Install the systemd user unit at
        /// `~/.config/systemd/user/air-drive.service` and enable it (FR-014).
        #[arg(long)]
        install_service: bool,
    },
}

/// Exit codes documented in `contracts/cli.md`.
#[derive(Debug, Clone, Copy)]
#[repr(i32)]
pub enum ExitCode {
    /// Success.
    Ok = 0,
    /// Uncaught error.
    GenericError = 1,
    /// OAuth error during `link` (FR-001).
    OauthError = 2,
    /// Network failure during `link`.
    NetworkError = 3,
    /// Local path supplied to `map` doesn't exist or isn't a directory.
    MapLocalInvalid = 4,
    /// Remote folder supplied to `map` cannot be resolved.
    MapRemoteUnresolvable = 5,
    /// Single-instance lock held by another live daemon (FR-017).
    LockHeld = 6,
    /// `pause` / `resume` invoked but no running daemon found.
    NoDaemonRunning = 7,
    /// `unlink` refused because the daemon is running.
    UnlinkWhileRunning = 8,
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::CommandFactory;

    #[test]
    fn clap_definition_is_valid() {
        // `debug_assert` validates the CLI tree (no duplicate arg names, etc.).
        Cli::command().debug_assert();
    }

    #[test]
    fn parses_link_with_label() {
        let cli = Cli::try_parse_from(["air-drive", "link", "--account-label", "perso"])
            .expect("link parses");
        match cli.command {
            Command::Link { account_label } => {
                assert_eq!(account_label.as_deref(), Some("perso"));
            }
            _ => panic!("expected Link variant"),
        }
    }

    #[test]
    fn parses_map_with_positional_args() {
        let cli = Cli::try_parse_from(["air-drive", "map", "/home/a/d", "path:My Drive/Sync"])
            .expect("map parses");
        match cli.command {
            Command::Map {
                local_path,
                remote_folder,
            } => {
                assert_eq!(local_path, PathBuf::from("/home/a/d"));
                assert_eq!(remote_folder, "path:My Drive/Sync");
            }
            _ => panic!("expected Map variant"),
        }
    }

    #[test]
    fn parses_start_with_initial_sync_and_poll_interval() {
        let cli = Cli::try_parse_from([
            "air-drive",
            "start",
            "--initial-sync",
            "--remote-poll-interval",
            "20",
        ])
        .expect("start parses");
        match cli.command {
            Command::Start {
                initial_sync,
                remote_poll_interval,
            } => {
                assert!(initial_sync);
                assert_eq!(remote_poll_interval, Some(20));
            }
            _ => panic!("expected Start variant"),
        }
    }

    #[test]
    fn parses_status_json() {
        let cli = Cli::try_parse_from(["air-drive", "status", "--json"]).expect("status parses");
        assert!(matches!(cli.command, Command::Status { json: true }));
    }

    #[test]
    fn global_flags_apply_before_subcommand() {
        let cli = Cli::try_parse_from([
            "air-drive",
            "-vv",
            "--config-dir",
            "/tmp/cfg",
            "--no-download-rclone",
            "pause",
        ])
        .expect("globals parse");
        assert_eq!(cli.verbose, 2);
        assert_eq!(cli.config_dir, Some(PathBuf::from("/tmp/cfg")));
        assert!(cli.no_download_rclone);
        assert!(matches!(cli.command, Command::Pause));
    }

    #[test]
    fn missing_subcommand_errors() {
        let res = Cli::try_parse_from(["air-drive"]);
        assert!(res.is_err());
    }

    #[test]
    fn exit_code_values_match_contract() {
        // Frozen by contracts/cli.md — anything that doesn't match here breaks the
        // documented stability promise.
        assert_eq!(ExitCode::Ok as i32, 0);
        assert_eq!(ExitCode::GenericError as i32, 1);
        assert_eq!(ExitCode::OauthError as i32, 2);
        assert_eq!(ExitCode::NetworkError as i32, 3);
        assert_eq!(ExitCode::MapLocalInvalid as i32, 4);
        assert_eq!(ExitCode::MapRemoteUnresolvable as i32, 5);
        assert_eq!(ExitCode::LockHeld as i32, 6);
        assert_eq!(ExitCode::NoDaemonRunning as i32, 7);
        assert_eq!(ExitCode::UnlinkWhileRunning as i32, 8);
    }
}
