//! Clap CLI surface for the `air-drive` binary.
//!
//! Single source of truth for the user-visible commands. Each subcommand resolves to
//! one of [`Command`]'s variants and is dispatched via [`dispatch`]; the actual
//! subcommand handlers live in sibling modules ([`link`], [`map`], [`start`],
//! [`unlink`], [`setup`]).

pub mod init;
pub mod interactive;
pub mod link;
pub mod map;
pub mod pause;
pub mod resume;
pub mod runtime;
pub mod setup;
pub mod shell;
pub mod start;
pub mod status;
pub mod stop;
pub mod unlink;

use std::path::PathBuf;

use clap::{Parser, Subcommand};

use crate::error::{Error, Result};

/// Top-level CLI definition. Generated by clap from the struct.
#[derive(Debug, Parser)]
#[command(
    name = "air-drive",
    version,
    about = "Open source Google Drive sync daemon for Linux",
    long_about = None,
)]
pub struct Cli {
    /// Override the XDG config directory (default `$XDG_CONFIG_HOME/air-drive`).
    #[arg(long, global = true, value_name = "PATH")]
    pub config_dir: Option<PathBuf>,

    /// Duplicate logs to this file in addition to stderr.
    #[arg(long, global = true, value_name = "PATH")]
    pub log_file: Option<PathBuf>,

    /// Increase log verbosity. Repeatable: `-v` info, `-vv` debug, `-vvv` trace.
    #[arg(short = 'v', long, global = true, action = clap::ArgAction::Count)]
    pub verbose: u8,

    /// Disable the post-install rclone auto-download. The daemon will fail at startup
    /// if `rclone` is not found via config / `$PATH` / cache.
    #[arg(long, global = true)]
    pub no_download_rclone: bool,

    /// Subcommand to dispatch.
    #[command(subcommand)]
    pub command: Command,
}

/// Every subcommand of `air-drive`.
#[derive(Debug, Subcommand)]
pub enum Command {
    /// Link a Google Drive account via the desktop OAuth flow.
    Link {
        /// Human-friendly label stored alongside the account. Defaults to the
        /// captured email.
        #[arg(long, value_name = "LABEL")]
        account_label: Option<String>,
    },
    /// Record the local↔remote folder mapping.
    Map {
        /// Local folder path (created on the fly if missing).
        local_path: PathBuf,
        /// Remote folder, one of: Drive file ID, Drive folder URL, or
        /// `path:My Drive/Sync` notation.
        remote_folder: String,
    },
    /// Run the daemon in the foreground.
    ///
    /// On the first start of a mapping (empty `drive_change_cursor`) the daemon
    /// performs the initial reconciliation automatically; on an interactive
    /// terminal it asks first so a wrong folder can be vetoed.
    Start {
        /// Override `daemon.remote_poll_interval_seconds` (clamped to 10..=60).
        #[arg(long, value_name = "SECONDS")]
        remote_poll_interval: Option<u64>,
        /// Detach and run the daemon in the background, returning immediately.
        /// Stdout/stderr are redirected to `<config-dir>/daemon.log`. For an
        /// always-on, supervised service prefer the systemd unit
        /// (`air-drive setup --install-service`). Stop it with `air-drive stop`.
        #[arg(short = 'd', long)]
        detached: bool,
    },
    /// Signal a running daemon to pause sync.
    Pause,
    /// Signal a paused daemon to resume sync.
    Resume,
    /// Signal a running daemon to shut down gracefully.
    Stop,
    /// Print the current daemon state.
    Status {
        /// Emit JSON matching `contracts/status.schema.json` instead of the
        /// human-readable summary.
        #[arg(long)]
        json: bool,
    },
    /// Remove the linked account, tokens, and mapping.
    Unlink {
        /// Skip the interactive confirmation prompt.
        #[arg(short = 'y', long)]
        yes: bool,
    },
    /// Interactive first-time setup: link → map → start.
    ///
    /// `--install-service` and `--uninstall-service` manage the systemd user
    /// unit and are mutually exclusive.
    Setup {
        /// Install the systemd user unit at
        /// `~/.config/systemd/user/air-drive.service` and enable it.
        #[arg(long)]
        install_service: bool,
        /// Reverse `--install-service`: stop and disable the systemd user
        /// unit, remove `~/.config/systemd/user/air-drive.service`, and
        /// refresh the systemd user-scope cache. Idempotent — exits 0 even
        /// when there is nothing to remove. Leaves config, state, tokens,
        /// account, mapping, watched folder, and binary untouched.
        #[arg(long, conflicts_with = "install_service")]
        uninstall_service: bool,
    },
    /// Bootstrap a personal Google Cloud OAuth client (Desktop) via the GCP
    /// Console, then write `[oauth]` into `config.toml`. Required when the
    /// embedded client_id is unusable (e.g. invalid_client errors).
    Init {
        /// Overwrite an existing `[oauth].client_id` in config.toml.
        #[arg(long)]
        force: bool,
        /// Run `air-drive link` immediately after writing the config.
        #[arg(long)]
        link: bool,
    },
    /// Manage desktop shell integration: per-file sync-status emblems in the
    /// file manager (GNOME Files / Nautilus on Linux).
    Shell {
        /// What to do: `install`, `uninstall`, or `status`.
        #[command(subcommand)]
        action: shell::ShellAction,
    },
    /// Open the Google link a native-Doc shortcut (`.gdoc`/`.gsheet`/…) points
    /// to. Invoked by the desktop file association `shell install` registers;
    /// not meant to be run by hand.
    #[command(hide = true)]
    OpenShortcut {
        /// Path to the shortcut file.
        path: PathBuf,
    },
}

/// Exit codes documented in the README.
#[derive(Debug, Clone, Copy)]
#[repr(i32)]
pub enum ExitCode {
    /// Success.
    Ok = 0,
    /// Uncaught error.
    GenericError = 1,
    /// OAuth error during `link`.
    OauthError = 2,
    /// Network failure during `link`.
    NetworkError = 3,
    /// Local path supplied to `map` doesn't exist or isn't a directory.
    MapLocalInvalid = 4,
    /// Remote folder supplied to `map` cannot be resolved.
    MapRemoteUnresolvable = 5,
    /// Single-instance lock held by another live daemon.
    LockHeld = 6,
    /// `pause` / `resume` invoked but no running daemon found.
    NoDaemonRunning = 7,
    /// `unlink` refused because the daemon is running.
    UnlinkWhileRunning = 8,
}

/// Dispatch the parsed CLI to the right subcommand handler.
///
/// Returns the `ExitCode` the binary should propagate. Errors propagate out so the
/// caller can log them; the caller maps them to [`ExitCode::GenericError`] unless the
/// error variant is one the subcommand handlers haven't already translated to a
/// typed exit code (e.g. lock contention → [`ExitCode::LockHeld`] handled inside
/// `start::run`).
pub async fn dispatch(cli: Cli) -> Result<ExitCode> {
    let cfg = crate::cli::runtime::resolve_paths(cli.config_dir.as_deref())
        .and_then(|p| crate::cli::runtime::load_config(&p))?;
    match cli.command {
        Command::Link { account_label } => {
            link::run(cli.config_dir.as_deref(), &cfg, account_label).await
        }
        Command::Map {
            local_path,
            remote_folder,
        } => map::run(cli.config_dir.as_deref(), &cfg, local_path, remote_folder).await,
        Command::Start {
            remote_poll_interval,
            detached,
        } => {
            start::run(
                cli.config_dir.as_deref(),
                &cfg,
                remote_poll_interval,
                cli.no_download_rclone,
                detached,
            )
            .await
        }
        Command::Pause => pause::run(cli.config_dir.as_deref()).await,
        Command::Resume => resume::run(cli.config_dir.as_deref()).await,
        Command::Stop => stop::run(cli.config_dir.as_deref()).await,
        Command::Status { json } => status::run(cli.config_dir.as_deref(), json).await,
        Command::Unlink { yes } => unlink::run(cli.config_dir.as_deref(), yes).await,
        Command::Setup {
            install_service,
            uninstall_service,
        } => {
            setup::run(
                cli.config_dir.as_deref(),
                install_service,
                uninstall_service,
            )
            .await
        }
        Command::Init { force, link } => init::run(cli.config_dir.as_deref(), force, link).await,
        Command::Shell { action } => shell::run(cli.config_dir.as_deref(), action).await,
        Command::OpenShortcut { path } => shell::open_shortcut(&path),
    }
}

/// Best-effort mapping of an [`Error`] to an [`ExitCode`]. Subcommand handlers usually
/// translate domain-specific errors to typed exit codes themselves; this fallback
/// only catches the ones that fell through.
pub fn fallback_exit_code(e: &Error) -> ExitCode {
    match e {
        Error::Lock { .. } => ExitCode::LockHeld,
        Error::Oauth(_) => ExitCode::OauthError,
        Error::Drive(_) => ExitCode::NetworkError,
        _ => ExitCode::GenericError,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::CommandFactory;

    #[test]
    fn clap_definition_is_valid() {
        // `debug_assert` validates the CLI tree (no duplicate arg names, etc.).
        Cli::command().debug_assert();
    }

    #[test]
    fn parses_link_with_label() {
        let cli = Cli::try_parse_from(["air-drive", "link", "--account-label", "perso"])
            .expect("link parses");
        match cli.command {
            Command::Link { account_label } => {
                assert_eq!(account_label.as_deref(), Some("perso"));
            }
            _ => panic!("expected Link variant"),
        }
    }

    #[test]
    fn parses_map_with_positional_args() {
        let cli = Cli::try_parse_from(["air-drive", "map", "/home/a/d", "path:My Drive/Sync"])
            .expect("map parses");
        match cli.command {
            Command::Map {
                local_path,
                remote_folder,
            } => {
                assert_eq!(local_path, PathBuf::from("/home/a/d"));
                assert_eq!(remote_folder, "path:My Drive/Sync");
            }
            _ => panic!("expected Map variant"),
        }
    }

    #[test]
    fn parses_start_with_poll_interval() {
        let cli = Cli::try_parse_from(["air-drive", "start", "--remote-poll-interval", "20"])
            .expect("start parses");
        match cli.command {
            Command::Start {
                remote_poll_interval,
                detached,
            } => {
                assert_eq!(remote_poll_interval, Some(20));
                assert!(!detached, "detached defaults to false");
            }
            _ => panic!("expected Start variant"),
        }
    }

    #[test]
    fn parses_start_detached_short_and_long() {
        for flag in ["-d", "--detached"] {
            let cli = Cli::try_parse_from(["air-drive", "start", flag]).expect("start parses");
            match cli.command {
                Command::Start { detached, .. } => assert!(detached, "{flag} should set detached"),
                _ => panic!("expected Start variant"),
            }
        }
    }

    #[test]
    fn parses_status_json() {
        let cli = Cli::try_parse_from(["air-drive", "status", "--json"]).expect("status parses");
        assert!(matches!(cli.command, Command::Status { json: true }));
    }

    #[test]
    fn parses_shell_subcommands() {
        let cli = Cli::try_parse_from(["air-drive", "shell", "install", "--skip-deps"])
            .expect("shell install parses");
        assert!(matches!(
            cli.command,
            Command::Shell {
                action: shell::ShellAction::Install { skip_deps: true }
            }
        ));

        let cli = Cli::try_parse_from(["air-drive", "shell", "uninstall"])
            .expect("shell uninstall parses");
        assert!(matches!(
            cli.command,
            Command::Shell {
                action: shell::ShellAction::Uninstall
            }
        ));

        let cli =
            Cli::try_parse_from(["air-drive", "shell", "status"]).expect("shell status parses");
        assert!(matches!(
            cli.command,
            Command::Shell {
                action: shell::ShellAction::Status
            }
        ));
    }

    #[test]
    fn global_flags_apply_before_subcommand() {
        let cli = Cli::try_parse_from([
            "air-drive",
            "-vv",
            "--config-dir",
            "/tmp/cfg",
            "--no-download-rclone",
            "pause",
        ])
        .expect("globals parse");
        assert_eq!(cli.verbose, 2);
        assert_eq!(cli.config_dir, Some(PathBuf::from("/tmp/cfg")));
        assert!(cli.no_download_rclone);
        assert!(matches!(cli.command, Command::Pause));
    }

    #[test]
    fn missing_subcommand_errors() {
        let res = Cli::try_parse_from(["air-drive"]);
        assert!(res.is_err());
    }

    #[test]
    fn exit_code_values_match_contract() {
        // Frozen contract — anything that doesn't match here breaks the documented
        // stability promise.
        assert_eq!(ExitCode::Ok as i32, 0);
        assert_eq!(ExitCode::GenericError as i32, 1);
        assert_eq!(ExitCode::OauthError as i32, 2);
        assert_eq!(ExitCode::NetworkError as i32, 3);
        assert_eq!(ExitCode::MapLocalInvalid as i32, 4);
        assert_eq!(ExitCode::MapRemoteUnresolvable as i32, 5);
        assert_eq!(ExitCode::LockHeld as i32, 6);
        assert_eq!(ExitCode::NoDaemonRunning as i32, 7);
        assert_eq!(ExitCode::UnlinkWhileRunning as i32, 8);
    }
}
